### ISSUE TITLE
您好，我做了一个 Alfred Workflow 把图片上传到微博，用到了您这个项目的 微博 - 登陆. py，请问我可以把我的 Workflow 打包发布吗？

### ISSUE THREAD

**Issue by cielpy** [alicewish/Python-Learning#1]
没有看到您在项目里放 License，所以问一下

**Comment by alicewish** [comment]
代码出处见
http://www.trytofix.com/2016/04/06/python%E6%A8%A1%E6%8B%9F%E5%BE%AE%E5%8D%9A%E7%99%BB%E9%99%86/
https://github.com/trytofix/hexo_weibo_image/blob/master/weibo_util.py

**Comment by cielpy** [comment]
好的，谢谢
